(function (root, factory) {
  if (typeof module === 'object' && module.exports) {
    module.exports = factory();
  } else {
    root.GSVRVenueData = factory();
  }
})(typeof self !== 'undefined' ? self : this, function () {
  'use strict';

  return {
    topVenueBases: [
      "AAAI",
      "AAAI/IAAI",
      "ACL",
      "ACL/IJCNLP",
      "ACM Conference on Computer and Communications Security",
      "ACM Trans. Embed. Comput. Syst.",
      "ACM Trans. Embedded Comput. Syst.",
      "ACM Trans. Graph.",
      "ASE",
      "ASPLOS",
      "Bioinform.",
      "Bioinformatics",
      "Bioinformatics [ISMB/ECCB]",
      "CAV",
      "CCS",
      "CHI",
      "COLING-ACL",
      "Comput. Graph. Forum",
      "CRYPTO",
      "CSL-LICS",
      "CVPR",
      "DAC",
      "EC",
      "ECCV",
      "EMNLP",
      "EMNLP-CoNLL",
      "EMNLP-IJCNLP",
      "EMNLP/IJCNLP",
      "EMSOFT",
      "ESEC/SIGSOFT FSE",
      "EUROCRYPT",
      "EUROGRAPHICS",
      "FAST",
      "FOCS",
      "FSE",
      "HRI",
      "HPCA",
      "HLT-NAACL",
      "ICCAD",
      "ICCV",
      "ICDE",
      "ICFP",
      "ICML",
      "ICMLA",
      "ICRA",
      "ICSE",
      "ICST",
      "ICS",
      "IJCNN",
      "IJCAI",
      "INFOCOM",
      "IPSN",
      "ISCA",
      "ISMB",
      "ISMB (Supplement of Bioinformatics)",
      "ISMB/ECCB (Supplement of Bioinformatics)",
      "ISSTA",
      "KDD",
      "LICS",
      "MICRO",
      "MOBICOM",
      "MOBIHOC",
      "MobiSys",
      "NAACL",
      "NAACL-HLT",
      "NAACL (Long Papers)",
      "NDSS",
      "NSDI",
      "NeurIPS",
      "NIPS",
      "OSDI",
      "OOPSLA",
      "OOPSLA/ECOOP",
      "OOPSLA1",
      "OOPSLA2",
      "PACMPL",
      "PODS",
      "POPL",
      "PPoPP",
      "PPOPP",
      "PVLDB",
      "PLDI",
      "Proc. ACM Interact. Mob. Wearable Ubiquitous Technol.",
      "Proc. ACM Manag. Data",
      "Proc. ACM Meas. Anal. Comput. Syst.",
      "SIGMETRICS",
      "Proc. ACM Program. Lang.",
      "Proc. ACM Softw. Eng.",
      "Proc. VLDB Endow.",
      "RECOMB",
      "Robotics: Science and Systems",
      "RTAS",
      "RTSS",
      "S&P",
      "SOSP",
      "SIGCOMM",
      "SenSys",
      "SIGCSE",
      "SIGGRAPH",
      "SIGGRAPH Asia",
      "SIGMOD",
      "SIGMOD Conference",
      "SIGSOFT FSE",
      "SP",
      "SPLASH",
      "STOC",
      "TACAS",
      "TCC",
      "USENIX Annual Technical Conference",
      "USENIX Annual Technical Conference, General Track",
      "USENIX ATC",
      "USENIX Security",
      "USENIX Security Symposium",
      "UbiComp",
      "Ubicomp",
      "VLDB",
      "VR",
      "WINE",
      "WWW",
      "IEEE Trans. Vis. Comput. Graph.",
      "IEEE Visualization",
      "VIS"
    ],
    venueAliases: {
      "nips": "NeurIPS",
      "neurips": "NeurIPS",
      "mobicom": "MobiCom",
      "nsdi": "NSDI",
      "sensys": "SenSys",
      "ubicomp": "UbiComp",
      "sigmod conference": "SIGMOD",
      "s&p": "S&P",
      "sp": "S&P",
      "usenix security symposium": "USENIX Security",
      "usenix annual technical conference": "USENIX ATC",
      "usenix annual technical conference, general track": "USENIX ATC",
      "acm conference on computer and communications security": "CCS",
      "ieee visualization": "VIS",
      "pvldb": "VLDB",
      "proc. vldb endow.": "VLDB",
      "proc. acm softw. eng.": "FSE",
      "sigsoft fse": "FSE",
      "esec/sigsoft fse": "FSE",
      "oopsla1": "OOPSLA",
      "oopsla2": "OOPSLA",
      "proc. acm meas. anal. comput. syst.": "SIGMETRICS",
      "pomacs": "SIGMETRICS",
      "proc. acm interact. mob. wearable ubiquitous technol.": "UbiComp"
    },
    proceedingsByJournal: {
      ismbBioinformatics: {
        2024: { volume: "40", number: "Supplement_1" },
        2023: { volume: "39", number: "Supplement-1" },
        2022: { volume: "38", number: "Supplement_1" },
        2021: { volume: "37", number: "Supplement" },
        2020: { volume: "36", number: "Supplement-1" },
        2019: { volume: "35", number: "14" },
        2018: { volume: "34", number: "13" },
        2017: { volume: "33", number: "14" },
        2016: { volume: "32", number: "12" },
        2015: { volume: "31", number: "12" },
        2014: { volume: "30", number: "12" },
        2013: { volume: "29", number: "13" },
        2012: { volume: "28", number: "12" },
        2011: { volume: "27", number: "13" },
        2010: { volume: "26", number: "12" },
        2009: { volume: "25", number: "12" },
        2008: { volume: "24", number: "13" },
        2007: { volume: "23", number: "13" }
      },
      togSiggraph: {
        2024: { volume: "43", number: "4" },
        2023: { volume: "42", number: "4" },
        2022: { volume: "41", number: "4" },
        2021: { volume: "40", number: "4" },
        2020: { volume: "39", number: "4" },
        2019: { volume: "38", number: "4" },
        2018: { volume: "37", number: "4" },
        2017: { volume: "36", number: "4" },
        2016: { volume: "35", number: "4" },
        2015: { volume: "34", number: "4" },
        2014: { volume: "33", number: "4" },
        2013: { volume: "32", number: "4" },
        2012: { volume: "31", number: "4" },
        2011: { volume: "30", number: "4" },
        2010: { volume: "29", number: "4" },
        2009: { volume: "28", number: "3" },
        2008: { volume: "27", number: "3" },
        2007: { volume: "26", number: "3" },
        2006: { volume: "25", number: "3" },
        2005: { volume: "24", number: "3" },
        2004: { volume: "23", number: "3" },
        2003: { volume: "22", number: "3" },
        2002: { volume: "21", number: "3" }
      },
      togSiggraphAsia: {
        2024: { volume: "43", number: "6" },
        2023: { volume: "42", number: "6" },
        2022: { volume: "41", number: "6" },
        2021: { volume: "40", number: "6" },
        2020: { volume: "39", number: "6" },
        2019: { volume: "38", number: "6" },
        2018: { volume: "37", number: "6" },
        2017: { volume: "36", number: "6" },
        2016: { volume: "35", number: "6" },
        2015: { volume: "34", number: "6" },
        2014: { volume: "33", number: "6" },
        2013: { volume: "32", number: "6" },
        2012: { volume: "31", number: "6" },
        2011: { volume: "30", number: "6" },
        2010: { volume: "29", number: "6" },
        2009: { volume: "28", number: "5" },
        2008: { volume: "27", number: "5" }
      },
      cgfEurographics: {
        2024: { volume: "43", number: "2" },
        2023: { volume: "42", number: "2" },
        2022: { volume: "41", number: "2" },
        2021: { volume: "40", number: "2" },
        2020: { volume: "39", number: "2" },
        2019: { volume: "38", number: "2" },
        2018: { volume: "37", number: "2" },
        2017: { volume: "36", number: "2" },
        2016: { volume: "35", number: "2" },
        2015: { volume: "34", number: "2" },
        2014: { volume: "33", number: "2" },
        2013: { volume: "32", number: "2" },
        2012: { volume: "31", number: "2" },
        2011: { volume: "30", number: "2" },
        2010: { volume: "29", number: "2" },
        2009: { volume: "28", number: "2" },
        2008: { volume: "27", number: "2" },
        2007: { volume: "26", number: "3" },
        2006: { volume: "25", number: "3" },
        2005: { volume: "24", number: "3" },
        2004: { volume: "23", number: "3" },
        2003: { volume: "22", number: "3" },
        2002: { volume: "21", number: "3" },
        2001: { volume: "20", number: "3" },
        2000: { volume: "19", number: "3" },
        1999: { volume: "18", number: "3" },
        1998: { volume: "17", number: "3" },
        1997: { volume: "16", number: "3" },
        1996: { volume: "15", number: "3" },
        1995: { volume: "14", number: "3" },
        1994: { volume: "13", number: "3" },
        1993: { volume: "12", number: "3" },
        1992: { volume: "11", number: "3" }
      },
      tvcgVis: {
        2025: { volume: "31", number: "1" },
        2024: { volume: "30", number: "1" },
        2023: { volume: "29", number: "1" },
        2022: { volume: "28", number: "1" },
        2021: { volume: "27", number: "2" },
        2020: { volume: "26", number: "1" },
        2019: { volume: "25", number: "1" },
        2018: { volume: "24", number: "1" },
        2017: { volume: "23", number: "1" },
        2016: { volume: "22", number: "1" },
        2014: { volume: "20", number: "12" },
        2013: { volume: "19", number: "12" },
        2012: { volume: "18", number: "12" },
        2011: { volume: "17", number: "12" },
        2010: { volume: "16", number: "6" },
        2009: { volume: "15", number: "6" },
        2008: { volume: "14", number: "6" },
        2007: { volume: "13", number: "6" },
        2006: { volume: "12", number: "5" }
      },
      tvcgVr: {
        2025: { volume: "31", number: "5" },
        2024: { volume: "30", number: "5" },
        2023: { volume: "29", number: "5" },
        2022: { volume: "28", number: "5" },
        2021: { volume: "27", number: "5" },
        2020: { volume: "26", number: "5" },
        2019: { volume: "25", number: "5" },
        2018: { volume: "24", number: "4" },
        2017: { volume: "23", number: "4" },
        2016: { volume: "22", number: "4" },
        2015: { volume: "21", number: "4" },
        2014: { volume: "20", number: "4" },
        2013: { volume: "19", number: "4" },
        2012: { volume: "18", number: "4" }
      }
    }
  };
});
